pipeline {
  /* Generate docker container with python image with root user */
  agent { docker { image 'python:3.7.2' 
                    args '-u root:root' } } 
  stages {
    stage('build') {
      steps {
        sh 'pwd' /* verify current folder */
        sh 'python3 -m venv venv' /* generate virtual environment */
        sh 'ls venv/bin' /* verify content generated by venv */
        /* verify current user */
        sh 'echo *********user*************'
        sh 'id -u -n'
        sh 'echo **************************'
        
        /* change permissons to activate virtual environment */
        sh 'chmod 777 /var/jenkins_home/workspace/z_python_pipeline/venv'
        sh 'chmod 777 /var/jenkins_home/workspace/z_python_pipeline/venv/bin'
        sh 'chmod 777 /var/jenkins_home/workspace/z_python_pipeline/venv/bin/activate'
        
        /* activate virtual environment */
        sh './venv/bin/activate'
        
        /* install requirements for unit tests */
        sh 'pip3 install -r requirements.txt'
      }
    }
    stage('test') {
      steps {
        /* list installed libraries and run unit test */
        sh """
            echo ************post-activation*******************
            pip3 list
            python3 tests.py
           """
      }   
    }
  }
}